version: '2'
name: project-recruitment
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: my-grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    restart: unless-stopped
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=cluster
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
  mysql:
    image: mysql:latest
    container_name: etl-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - 3306:3306